name: Build and test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_server:
    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Execute npm ci
      run: npm ci
    - name: start server-be
      run: npm run server-be &
    - name: start server-fe
      run: npm run server-fe &
    - name: Execute tests
      run: npm test


