name: Build and test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Execute npm ci
      run: npm ci
    - name: Manualy update the config.js
      run: echo "export const settings = { host:'http://localhost:3030' };" > src/config.js 
    - name: start server-be
      run: npm run server-be &
    - name: start server-fe
      run: npm run server-fe &
    - name: install playwright browser
      run: npx playwright install
    - name: Execute tests
      run: npm test

  deploy_be:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to production server-be
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.SERVICE_ID_BE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

  deploy_fe:
    runs-on: ubuntu-latest
    needs: deploy_be
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to production server-fe
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.SERVICE_ID_FE }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
