name: Build and test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Execute npm ci
      run: npm ci
    - name: Manualy update the config.js
      run: echo "export const settings = { host:'https://localhost:3030'};" > src/config.js 
    - name: start server-be
      run: npm run server-be &
    - name: start server-fe
      run: npm run server-fe &
    - name: install playwright browser
      run: npx playwright install
    - name: Execute tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy to production server-be
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.BE_API_KEY }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
      - name: Deploy to production server-fe
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.FE_API_KEY }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
