name: Build and test 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Execute npm ci
      run: npm ci
    - name: execute playwrigt
      run: npx playright install
           npm init playwright@latest
    - name: Execute tests
      run: npm test
